version: '3.5'

services:

  backend:
    container_name: backend
    build: ./backend
    restart: always
    volumes:
      - ./backend/:/backend/:rw
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
    ports:
      - "3333:3333"

  db:
    container_name: db
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - aip_labs_local_data:/var/lib/postgresql/data
volumes:
  aip_labs_local_data:
    driver: local
